from __future__ import annotations

import re
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


class TestUdosWorkspaceExport(unittest.TestCase):
    def test_actc_overlay_export_specs_match_compiler_load_table(self) -> None:
        root = Path(__file__).resolve().parents[1]
        exporter_text = (root / "tools" / "export_udos_workspace.py").read_text(encoding="ascii")
        actc_text = (root / "src" / "tools_udos" / "actc" / "actc.asm").read_text(encoding="ascii")
        overlay_abi_text = (
            root / "src" / "tools_udos" / "actc" / "actc_overlay_abi.inc"
        ).read_text(encoding="ascii")

        pass_count_match = re.search(
            r"^ACTC_OVERLAY_PASS_COUNT\s*=\s*\$([0-9A-Fa-f]+)$",
            overlay_abi_text,
            re.MULTILINE,
        )
        self.assertIsNotNone(pass_count_match, "overlay ABI has no pass count")
        assert pass_count_match is not None
        pass_count = int(pass_count_match.group(1), 16)
        pass_ids = {
            int(match.group(1), 16)
            for match in re.finditer(
                r"^ACTC_OVERLAY_PASS_[A-Z0-9_]+\s*=\s*\$([0-9A-Fa-f]{2})$",
                overlay_abi_text,
                re.MULTILINE,
            )
            if int(match.group(1), 16) < pass_count
        }
        def overlay_selector(index: int) -> str:
            return str(index) if index < 10 else chr(ord("A") + index - 10)

        compiler_overlays = {f"ACTC_OVL{overlay_selector(index)}.BIN" for index in range(pass_count)}
        exporter_specs = {
            match.group(2).upper(): match.group(1)
            for match in re.finditer(
                r'\("(build_actc_overlay_[^"]+\.sh)",\s*"(ACTC_OVL[0-9A-Z]\.BIN)"\)',
                exporter_text,
            )
        }
        self.assertIn('.asciiz "!ACTC_OVL0.BIN"', actc_text)
        self.assertEqual(pass_ids, set(range(pass_count)))
        self.assertEqual(set(exporter_specs), compiler_overlays)
        for overlay_name, script_name in sorted(exporter_specs.items()):
            with self.subTest(overlay=overlay_name):
                self.assertTrue((root / "tools" / script_name).is_file(), script_name)

    def test_export_creates_udos_tree_with_guides_examples_and_libs(self) -> None:
        root = Path(__file__).resolve().parents[1]
        tool = root / "tools" / "export_udos_workspace.py"

        with tempfile.TemporaryDirectory() as tmpdir:
            output = Path(tmpdir) / "out"
            result = subprocess.run(
                [sys.executable, str(tool), "--output", str(output)],
                cwd=root,
                text=True,
                capture_output=True,
                check=False,
            )
            self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)

            image_root = output / "IMAGES" / "ACTION.DNP"
            self.assertTrue(image_root.is_dir())

            expected_dirs = ["BIN", "DOC", "LIB", "SRC"]
            for name in expected_dirs:
                self.assertTrue((image_root / name).is_dir(), name)

            self.assertTrue((image_root / "README.TXT").is_file())
            self.assertIn("D BIN", (image_root / "UDOSDIR.TXT").read_text(encoding="ascii"))
            self.assertIn("F README.TXT", (image_root / "UDOSDIR.TXT").read_text(encoding="ascii"))

            docs_dir = image_root / "DOC"
            self.assertTrue((docs_dir / "OPERATOR.TXT").is_file())
            self.assertTrue((docs_dir / "LANGUAGE.TXT").is_file())
            self.assertTrue((docs_dir / "INPUT1.TXT").is_file())
            self.assertTrue((docs_dir / "DBF1.TXT").is_file())
            self.assertTrue((docs_dir / "DEBUGGER.TXT").is_file())
            self.assertFalse((docs_dir / "VMABI.TXT").exists())
            self.assertFalse((docs_dir / "UDOSRESM.TXT").exists())
            self.assertIn("ActionC64U UDOS Operator Guide", (docs_dir / "OPERATOR.TXT").read_text(encoding="ascii"))
            debugger_doc = (docs_dir / "DEBUGGER.TXT").read_text(encoding="ascii")
            self.assertIn("ACTDBG Native Source Debugger", debugger_doc)
            self.assertIn("F3: step into one native instruction", debugger_doc)
            input1_doc = (docs_dir / "INPUT1.TXT").read_text(encoding="ascii")
            self.assertIn("INPUT1 Joystick And Mouse Library", input1_doc)
            self.assertIn("Joy(port) returns an active-high bitfield", input1_doc)
            self.assertIn("JoyBtn1(port) returns 1", input1_doc)
            self.assertIn("MousePoll(port) samples the selected control port", input1_doc)
            self.assertIn("MouseBtn2() returns 1", input1_doc)
            dbf1_doc = (docs_dir / "DBF1.TXT").read_text(encoding="ascii")
            self.assertIn("DBF1 Database Library", dbf1_doc)
            self.assertIn("DbfOpen(filename) stages an existing DBF file", dbf1_doc)
            self.assertIn("DbfDeleted(handle) returns 1", dbf1_doc)
            self.assertIn("DbfWriteByte(handle, offset, value)", dbf1_doc)
            self.assertIn("DbfAppend(handle) appends one blank current record", dbf1_doc)
            self.assertIn("DbfSave(handle) writes the staged DBF image", dbf1_doc)
            self.assertIn("DbfDelete(handle) sets the current record", dbf1_doc)
            self.assertIn("DbfUndelete(handle) clears the current record", dbf1_doc)
            self.assertIn("DbfHeaderLen(handle) returns the low byte", dbf1_doc)
            self.assertIn("DbfCreate(filename) stages a new empty zero-field DBF image", dbf1_doc)
            self.assertIn("RT_DBF_CREATE.OBJ", dbf1_doc)
            self.assertIn("RT_DBF_OPEN.OBJ", dbf1_doc)
            self.assertIn("RT_DBF_WRITEBYTE.OBJ", dbf1_doc)
            self.assertIn("RT_DBF_APPEND.OBJ", dbf1_doc)
            self.assertIn("RT_DBF_PACK.OBJ", dbf1_doc)
            self.assertIn("RT_DBF_SAVE.OBJ", dbf1_doc)
            self.assertIn("RT_DBF_DELETE.OBJ", dbf1_doc)
            self.assertIn("RT_DBF_UNDELETE.OBJ", dbf1_doc)
            self.assertIn("RT_DBF_DELETED.OBJ", dbf1_doc)
            self.assertIn("RT_DBF_HEADERLEN.OBJ", dbf1_doc)

            src_dir = image_root / "SRC"
            self.assertTrue((src_dir / "GFX1_DEMO.ACT").is_file())
            self.assertTrue((src_dir / "HELLO.ACT").is_file())
            self.assertTrue((src_dir / "INPUT1_DEMO.ACT").is_file())
            self.assertTrue((src_dir / "DBF1_DEMO.ACT").is_file())
            self.assertTrue((src_dir / "MATH1_DEMO.ACT").is_file())
            self.assertTrue((src_dir / "SIDSPR1_DEMO.ACT").is_file())
            self.assertTrue((src_dir / "MATH.ACT").is_file())
            self.assertTrue((src_dir / "ASMBLOCK_DEMO.ACT").is_file())
            gfx1_demo = (src_dir / "GFX1_DEMO.ACT").read_text(encoding="ascii")
            self.assertIn("ScreenCell(5,2,65)", gfx1_demo)
            self.assertIn("ColorCell(6,3,10)", gfx1_demo)
            self.assertIn("PROC main()", (src_dir / "HELLO.ACT").read_text(encoding="ascii"))
            input_demo = (src_dir / "INPUT1_DEMO.ACT").read_text(encoding="ascii")
            self.assertIn("Joy(2)", input_demo)
            self.assertIn("JoyBtn1(2)", input_demo)
            self.assertIn("JoyBtn2(2)", input_demo)
            self.assertIn("MousePoll(1)", input_demo)
            self.assertIn("MouseBtn1()", input_demo)
            self.assertIn("MouseBtn2()", input_demo)
            self.assertIn("JOY_UP+JOY_BUTTON1+JOY_BUTTON2", input_demo)
            self.assertIn("MOUSE_BUTTON1+MOUSE_BUTTON2", input_demo)
            dbf1_demo = (src_dir / "DBF1_DEMO.ACT").read_text(encoding="ascii")
            self.assertIn("DbfClose(handle)", dbf1_demo)
            self.assertIn("filename=12288", dbf1_demo)
            self.assertIn("handle=DbfOpen(filename)", dbf1_demo)
            self.assertIn("fields=DbfFieldCount(handle)", dbf1_demo)
            self.assertIn("fieldlen=DbfFieldLen(handle,1)", dbf1_demo)
            self.assertIn("moved=DbfGo(handle,2)", dbf1_demo)
            self.assertIn("deleted=DbfDeleted(handle)", dbf1_demo)
            self.assertIn("headerlen=DbfHeaderLen(handle)", dbf1_demo)
            self.assertIn("recordlen=DbfRecordLen(handle)", dbf1_demo)
            self.assertIn("total=DbfTotalRecs(handle)", dbf1_demo)
            self.assertIn("recno=DbfCurrRecNo(handle)", dbf1_demo)
            math1_demo = (src_dir / "MATH1_DEMO.ACT").read_text(encoding="ascii")
            self.assertIn("A=REAL(0-7)", math1_demo)
            self.assertIn("X=FAbs(A)", math1_demo)
            self.assertIn("PrintRE(X)", math1_demo)
            sidspr1_demo = (src_dir / "SIDSPR1_DEMO.ACT").read_text(encoding="ascii")
            self.assertIn("SidWave(1,SID_TRI+SID_SAW+SID_PULSE+SID_NOISE)", sidspr1_demo)
            self.assertIn("SpritePrio(2,SPR_BACK)", sidspr1_demo)
            asmblock_demo = (src_dir / "ASMBLOCK_DEMO.ACT").read_text(encoding="ascii")
            self.assertIn("ASMBLOCK [", asmblock_demo)
            self.assertIn("BNE DELAY", asmblock_demo)

            old_binary_pattern = "*." + ("A" + "VM")
            self.assertFalse(list(image_root.rglob(old_binary_pattern)))
            self.assertFalse(list(image_root.rglob("*.AVT")))

            lib_dir = image_root / "LIB"
            bundle = (lib_dir / "LIBMODS.DAT").read_text(encoding="ascii")
            self.assertIn("FILE libpstr.mod", bundle)
            self.assertTrue((lib_dir / "LIBPSTR.MOD").is_file())
            self.assertFalse((root / "src" / "tools_cpm").exists())
            expected_runtime_objs = {
                path.name.upper()
                for source_dir in [
                    root / "src" / "runtime" / "modules",
                    root / "src" / "runtime" / "udos_modules",
                ]
                for path in source_dir.glob("*.obj")
            }
            exported_runtime_objs = {path.name.upper() for path in lib_dir.glob("RT_*.OBJ")}
            missing_runtime_objs = sorted(expected_runtime_objs - exported_runtime_objs)
            self.assertFalse(
                missing_runtime_objs,
                "Runtime OBJ modules missing from exported LIB/: " + ", ".join(missing_runtime_objs),
            )
            self.assertTrue((lib_dir / "RT_PRINT_STR.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_F_ADD.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_F_ADDSUB_CORE.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_F_SUB.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_F_MUL.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_F_DIV.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_F_CMP.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_F_MIN.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_F_CLAMP.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_F_MAX.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_F_ABS.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_F_SQRT.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_I_MUL.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_I_DIV.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_PRINT_I.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_I_TO_F.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_F_TO_I.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_F_FRAC.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_F_MOD.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_F_HYPOT.OBJ").is_file())
            self.assertTrue((lib_dir / "MATH1.ACT").is_file())
            self.assertTrue((lib_dir / "GFX1.ACT").is_file())
            self.assertTrue((lib_dir / "RT_GFX_SCREEN_CELL.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_GFX_COLOR_CELL.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_GFX_BGCOLOR.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_GFX_BITMAP_FILL.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_GFX_MBITMAP_OFF.OBJ").is_file())
            self.assertTrue((lib_dir / "INPUT1.ACT").is_file())
            self.assertTrue((lib_dir / "RT_JOY.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_JP.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_JB1.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_JB2.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_JS.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_MP.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_MSEEN.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_MX.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_MY.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_MB.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_MB1.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_MB2.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_MS.OBJ").is_file())
            self.assertTrue((lib_dir / "DBF1.ACT").is_file())
            self.assertTrue((lib_dir / "RT_DBF_CREATE.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_OPEN.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_STATE.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_CLOSE.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_GO.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_FIELDCOUNT.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_FIELDLEN.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_READBYTE.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_WRITEBYTE.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_APPEND.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_PACK.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_SAVE.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_DELETE.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_UNDELETE.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_DELETED.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_HEADERLEN.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_RECORDLEN.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_TOTALRECS.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_DBF_CURRRECNO.OBJ").is_file())
            self.assertTrue((lib_dir / "SIDSPR1.ACT").is_file())
            self.assertTrue((lib_dir / "RT_SID_FREQ.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_SID_STATE.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_SPRITE_ON.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_SPRITE_PTR.OBJ").is_file())
            self.assertTrue((lib_dir / "RT_SPRITE_DATA.OBJ").is_file())
            gfx1_contents = (lib_dir / "GFX1.ACT").read_text(encoding="ascii")
            self.assertIn("PROC BgColor(BYTE color)", gfx1_contents)
            self.assertIn("PROC ScreenCell(BYTE x,BYTE y,BYTE ch)", gfx1_contents)
            self.assertIn("PROC BitmapCopy(CARD addr)", gfx1_contents)
            self.assertIn("PROC MBitmapOff()", gfx1_contents)
            input1_contents = (lib_dir / "INPUT1.ACT").read_text(encoding="ascii")
            self.assertIn("BYTE FUNC Joy(BYTE port)", input1_contents)
            self.assertIn("BYTE FUNC JoySeen(BYTE port)", input1_contents)
            self.assertIn("BYTE FUNC JoyBtn1(BYTE port)", input1_contents)
            self.assertIn("BYTE FUNC JoyBtn2(BYTE port)", input1_contents)
            self.assertIn("BYTE FUNC MousePoll(BYTE port)", input1_contents)
            self.assertIn("BYTE FUNC MouseSeen()", input1_contents)
            self.assertIn("BYTE FUNC MouseBtn()", input1_contents)
            self.assertIn("BYTE FUNC MouseBtn1()", input1_contents)
            self.assertIn("BYTE FUNC MouseBtn2()", input1_contents)
            dbf1_contents = (lib_dir / "DBF1.ACT").read_text(encoding="ascii")
            self.assertIn("BYTE FUNC DbfCreate(CARD filename)", dbf1_contents)
            self.assertIn("BYTE FUNC DbfOpen(CARD filename)", dbf1_contents)
            self.assertIn("PROC DbfClose(BYTE handle)", dbf1_contents)
            self.assertIn("BYTE FUNC DbfGo(BYTE handle,BYTE recno)", dbf1_contents)
            self.assertIn("BYTE FUNC DbfFieldCount(BYTE handle)", dbf1_contents)
            self.assertIn("BYTE FUNC DbfFieldLen(BYTE handle,BYTE field)", dbf1_contents)
            self.assertIn("BYTE FUNC DbfReadByte(BYTE handle,BYTE offset)", dbf1_contents)
            self.assertIn("BYTE FUNC DbfWriteByte(BYTE handle,BYTE offset,BYTE value)", dbf1_contents)
            self.assertIn("BYTE FUNC DbfAppend(BYTE handle)", dbf1_contents)
            self.assertIn("BYTE FUNC DbfPack(BYTE handle)", dbf1_contents)
            self.assertIn("BYTE FUNC DbfSave(BYTE handle)", dbf1_contents)
            self.assertIn("BYTE FUNC DbfDelete(BYTE handle)", dbf1_contents)
            self.assertIn("BYTE FUNC DbfUndelete(BYTE handle)", dbf1_contents)
            self.assertIn("BYTE FUNC DbfDeleted(BYTE handle)", dbf1_contents)
            self.assertIn("BYTE FUNC DbfHeaderLen(BYTE handle)", dbf1_contents)
            self.assertIn("BYTE FUNC DbfRecordLen(BYTE handle)", dbf1_contents)
            self.assertIn("BYTE FUNC DbfTotalRecs(BYTE handle)", dbf1_contents)
            self.assertIn("BYTE FUNC DbfCurrRecNo(BYTE handle)", dbf1_contents)
            sidspr1_contents = (lib_dir / "SIDSPR1.ACT").read_text(encoding="ascii")
            self.assertIn("BYTE CONST SID_PULSE=$40", sidspr1_contents)
            self.assertIn("BYTE CONST SPR_BACK=1", sidspr1_contents)
            self.assertIn("PROC SpriteData(BYTE n,CARD addr)", sidspr1_contents)
            self.assertIn("PROC SidFreq(BYTE v,CARD freq)", sidspr1_contents)
            self.assertIn("BYTE FUNC SidOsc3()", sidspr1_contents)
            math1_contents = (lib_dir / "MATH1.ACT").read_text(encoding="ascii")
            self.assertIn("PROC PrintR(REAL value)", math1_contents)
            self.assertIn("PROC PrintRE(REAL value)", math1_contents)
            self.assertIn("REAL FUNC FAbs(REAL value)", math1_contents)
            self.assertIn("REAL FUNC FSqrt(REAL value)", math1_contents)
            self.assertIn("REAL FUNC FSign(REAL value)", math1_contents)
            self.assertIn("REAL FUNC FTrunc(REAL value)", math1_contents)
            self.assertIn("REAL FUNC FFloor(REAL value)", math1_contents)
            self.assertIn("REAL FUNC FCeil(REAL value)", math1_contents)
            self.assertIn("REAL FUNC FRound(REAL value)", math1_contents)
            self.assertIn("REAL FUNC FFrac(REAL value)", math1_contents)
            self.assertIn("REAL FUNC FMod(REAL value,divisor)", math1_contents)
            self.assertIn("REAL FUNC FHypot(REAL x,y)", math1_contents)
            self.assertIn("REAL FUNC FMin(REAL left,right)", math1_contents)
            self.assertIn("REAL FUNC FMax(REAL left,right)", math1_contents)
            self.assertIn("REAL FUNC FClamp(REAL value,lower,upper)", math1_contents)
            self.assertIn("REAL CONST MATH_PI=3.14159265358979323846", math1_contents)
            self.assertIn("REAL CONST MATH_SQRT2=1.41421356237309504880", math1_contents)
            self.assertNotIn("MODULE MATH1", math1_contents)
            self.assertIn("Include this file before or after the application MODULE", math1_contents)
            self.assertIn("REAL arithmetic/comparison operators", math1_contents)
            i_to_f_contents = (lib_dir / "RT_I_TO_F.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_i_to_f 0 88", i_to_f_contents)
            self.assertIn("b M", i_to_f_contents)
            self.assertIn("m 85 04 86 05", i_to_f_contents)
            self.assertIn("n rt_i_to_f", i_to_f_contents)
            i_mul_contents = (lib_dir / "RT_I_MUL.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_i_mul 0 55", i_mul_contents)
            self.assertIn("b M", i_mul_contents)
            self.assertIn("n rt_i_mul", i_mul_contents)
            i_div_contents = (lib_dir / "RT_I_DIV.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_i_div 0 65", i_div_contents)
            self.assertIn("b M", i_div_contents)
            self.assertIn("n rt_i_div", i_div_contents)
            print_i_contents = (lib_dir / "RT_PRINT_I.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_print_i 0 334", print_i_contents)
            self.assertIn("b M", print_i_contents)
            self.assertIn("n rt_print_i", print_i_contents)
            s_to_f_contents = (lib_dir / "RT_S_TO_F.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_s_to_f 0 123", s_to_f_contents)
            self.assertIn("b M", s_to_f_contents)
            self.assertIn("m 85 04 86 05", s_to_f_contents)
            self.assertIn("n rt_s_to_f", s_to_f_contents)
            print_f_contents = (lib_dir / "RT_PRINT_F.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_print_f 0 909", print_f_contents)
            self.assertIn("x RT_PRINT_F_L1 723 1", print_f_contents)
            self.assertIn("b M", print_f_contents)
            self.assertNotIn("\nu ", print_f_contents)
            self.assertIn("r 243 x RT_PRINT_F_L1", print_f_contents)
            self.assertIn("n rt_print_f", print_f_contents)
            f_to_i_contents = (lib_dir / "RT_F_TO_I.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_f_to_i 0 124", f_to_i_contents)
            self.assertIn("b M", f_to_i_contents)
            self.assertIn("m A0 03 B1 02", f_to_i_contents)
            self.assertIn("n rt_f_to_i", f_to_i_contents)
            f_add_contents = (lib_dir / "RT_F_ADD.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_f_add 0 6", f_add_contents)
            self.assertIn("b u0M", f_add_contents)
            self.assertIn("u rt_f_addsub_core", f_add_contents)
            self.assertIn("r 3 u0", f_add_contents)
            self.assertIn("n rt_f_add", f_add_contents)
            f_sub_contents = (lib_dir / "RT_F_SUB.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_f_sub 0 6", f_sub_contents)
            self.assertIn("b u0M", f_sub_contents)
            self.assertIn("u rt_f_addsub_core", f_sub_contents)
            self.assertIn("r 3 u0", f_sub_contents)
            self.assertIn("n rt_f_sub", f_sub_contents)
            f_addsub_contents = (lib_dir / "RT_F_ADDSUB_CORE.OBJ").read_text(
                encoding="ascii"
            )
            self.assertIn("x rt_f_addsub_core 0 703", f_addsub_contents)
            self.assertIn("b u0M", f_addsub_contents)
            self.assertIn("u rt_f_special", f_addsub_contents)
            self.assertIn("r 3 u0", f_addsub_contents)
            self.assertIn("n rt_f_addsub_core", f_addsub_contents)
            f_mul_contents = (lib_dir / "RT_F_MUL.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_f_mul 0 518", f_mul_contents)
            self.assertIn("x RT_F_MUL_ROUND 377 1", f_mul_contents)
            self.assertIn("b u0M", f_mul_contents)
            self.assertIn("u rt_f_special", f_mul_contents)
            self.assertIn("r 333 x RT_F_MUL_ROUND", f_mul_contents)
            self.assertIn("n rt_f_mul", f_mul_contents)
            f_div_contents = (lib_dir / "RT_F_DIV.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_f_div 0 653", f_div_contents)
            self.assertIn("x RT_F_DIV_ROUND 484 1", f_div_contents)
            self.assertIn("b u0M", f_div_contents)
            self.assertIn("u rt_f_special", f_div_contents)
            self.assertIn("r 433 x RT_F_DIV_ROUND", f_div_contents)
            self.assertIn("n rt_f_div", f_div_contents)
            f_cmp_contents = (lib_dir / "RT_F_CMP.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_f_cmp 0 137", f_cmp_contents)
            self.assertIn("b u0M", f_cmp_contents)
            self.assertIn("m A9 05 20 00 00", f_cmp_contents)
            self.assertIn("u rt_f_special", f_cmp_contents)
            self.assertIn("r 3 u0", f_cmp_contents)
            self.assertNotIn("u rt_f_to_i", f_cmp_contents)
            self.assertIn("n rt_f_cmp", f_cmp_contents)
            for name in ("min", "max"):
                f_select_contents = (lib_dir / f"RT_F_{name.upper()}.OBJ").read_text(
                    encoding="ascii"
                )
                self.assertIn(f"x rt_f_{name} 0 77", f_select_contents)
                self.assertIn("b u0M", f_select_contents)
                self.assertIn("u rt_f_cmp", f_select_contents)
                self.assertIn("r 1 u0", f_select_contents)
                self.assertIn(f"n rt_f_{name}", f_select_contents)
            f_abs_contents = (lib_dir / "RT_F_ABS.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_f_abs 0 18", f_abs_contents)
            self.assertIn("b M", f_abs_contents)
            self.assertIn("m A0 00 B1 02", f_abs_contents)
            self.assertIn("n rt_f_abs", f_abs_contents)
            f_trunc_contents = (lib_dir / "RT_F_TRUNC.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_f_trunc 0 107", f_trunc_contents)
            self.assertIn("b M", f_trunc_contents)
            self.assertNotIn("\nu ", f_trunc_contents)
            self.assertIn("n rt_f_trunc", f_trunc_contents)
            f_floor_contents = (lib_dir / "RT_F_FLOOR.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_f_floor 0 135", f_floor_contents)
            self.assertIn("b u0M", f_floor_contents)
            self.assertIn("u rt_f_trunc", f_floor_contents)
            self.assertIn("r 13 u0", f_floor_contents)
            self.assertIn("n rt_f_floor", f_floor_contents)
            f_ceil_contents = (lib_dir / "RT_F_CEIL.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_f_ceil 0 42", f_ceil_contents)
            self.assertIn("b u0M", f_ceil_contents)
            self.assertIn("u rt_f_floor", f_ceil_contents)
            self.assertIn("r 31 u0", f_ceil_contents)
            self.assertIn("n rt_f_ceil", f_ceil_contents)
            f_round_contents = (lib_dir / "RT_F_ROUND.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_f_round 0 152", f_round_contents)
            self.assertIn("b u0M", f_round_contents)
            self.assertIn("u rt_f_trunc", f_round_contents)
            self.assertIn("r 13 u0", f_round_contents)
            self.assertIn("n rt_f_round", f_round_contents)
            f_frac_contents = (lib_dir / "RT_F_FRAC.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_f_frac 0 93", f_frac_contents)
            self.assertIn("b u0u1M", f_frac_contents)
            self.assertIn("u rt_f_trunc", f_frac_contents)
            self.assertIn("u rt_f_sub", f_frac_contents)
            self.assertIn("r 43 u0", f_frac_contents)
            self.assertIn("r 76 u1", f_frac_contents)
            self.assertIn("n rt_f_frac", f_frac_contents)
            f_mod_contents = (lib_dir / "RT_F_MOD.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_f_mod 0 245", f_mod_contents)
            self.assertIn("b u0u1u2u3M", f_mod_contents)
            self.assertIn("u rt_f_div", f_mod_contents)
            self.assertIn("u rt_f_trunc", f_mod_contents)
            self.assertIn("u rt_f_mul", f_mod_contents)
            self.assertIn("u rt_f_sub", f_mod_contents)
            self.assertIn("r 121 u0", f_mod_contents)
            self.assertIn("r 210 u3", f_mod_contents)
            self.assertIn("n rt_f_mod", f_mod_contents)
            f_hypot_contents = (lib_dir / "RT_F_HYPOT.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_f_hypot 0 503", f_hypot_contents)
            self.assertIn("b u0u1u2u3u4u5u6M", f_hypot_contents)
            for dependency in (
                "rt_f_abs",
                "rt_f_max",
                "rt_f_min",
                "rt_f_div",
                "rt_f_mul",
                "rt_f_add",
                "rt_f_sqrt",
            ):
                self.assertIn(f"u {dependency}", f_hypot_contents)
            self.assertIn("r 57 u0", f_hypot_contents)
            self.assertIn("r 432 u4", f_hypot_contents)
            self.assertIn("n rt_f_hypot", f_hypot_contents)
            f_sqrt_contents = (lib_dir / "RT_F_SQRT.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_f_sqrt 0 506", f_sqrt_contents)
            self.assertIn("x RT_F_SQRT_SQRT_LOOP 236 1", f_sqrt_contents)
            self.assertIn("b u0M", f_sqrt_contents)
            self.assertIn("u rt_f_special", f_sqrt_contents)
            self.assertIn("r 400 x RT_F_SQRT_SQRT_LOOP", f_sqrt_contents)
            self.assertIn("n rt_f_sqrt", f_sqrt_contents)
            f_special_contents = (lib_dir / "RT_F_SPECIAL.OBJ").read_text(
                encoding="ascii"
            )
            self.assertIn("x rt_f_special 0 419", f_special_contents)
            self.assertIn("x RT_F_SPECIAL_STORE_QNAN 254 1", f_special_contents)
            self.assertIn("b M", f_special_contents)
            self.assertNotIn("\nu ", f_special_contents)
            self.assertIn("n rt_f_special", f_special_contents)
            joy_contents = (lib_dir / "RT_JOY.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_joy 0 93", joy_contents)
            self.assertIn("b M", joy_contents)
            self.assertIn("n rt_joy", joy_contents)
            jp_contents = (lib_dir / "RT_JP.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_jp 0 21", jp_contents)
            self.assertIn("u rt_joy", jp_contents)
            self.assertIn("u rt_js", jp_contents)
            self.assertIn("m 85 02 20 00 00", jp_contents)
            self.assertIn("r 15 u1", jp_contents)
            js_contents = (lib_dir / "RT_JS.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_js 0 2", js_contents)
            self.assertIn("m 00 00", js_contents)
            mp_contents = (lib_dir / "RT_MP.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_mp 0 357", mp_contents)
            self.assertIn("u rt_ms", mp_contents)
            self.assertIn("r 354 u0", mp_contents)
            dbf_create_contents = (lib_dir / "RT_DBF_CREATE.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_dbf_create 0 143", dbf_create_contents)
            self.assertIn("u rt_dbf_state", dbf_create_contents)
            self.assertIn("20 3C CF", dbf_create_contents)
            self.assertIn("r 138 u0", dbf_create_contents)
            dbf_deleted_contents = (lib_dir / "RT_DBF_DELETED.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_dbf_deleted 0 15", dbf_deleted_contents)
            self.assertIn("u rt_dbf_readbyte", dbf_deleted_contents)
            self.assertIn("C9 2A", dbf_deleted_contents)
            self.assertIn("r 3 u0", dbf_deleted_contents)
            dbf_delete_contents = (lib_dir / "RT_DBF_DELETE.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_dbf_delete 0 8", dbf_delete_contents)
            self.assertIn("u rt_dbf_writebyte", dbf_delete_contents)
            self.assertIn("A2 00 A0 2A", dbf_delete_contents)
            self.assertIn("r 5 u0", dbf_delete_contents)
            dbf_undelete_contents = (lib_dir / "RT_DBF_UNDELETE.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_dbf_undelete 0 8", dbf_undelete_contents)
            self.assertIn("u rt_dbf_writebyte", dbf_undelete_contents)
            self.assertIn("A2 00 A0 20", dbf_undelete_contents)
            self.assertIn("r 5 u0", dbf_undelete_contents)
            dbf_readfieldbyte_contents = (lib_dir / "RT_DBF_READFIELDBYTE.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_dbf_readfieldbyte 0 92", dbf_readfieldbyte_contents)
            self.assertIn("u rt_dbf_fieldlen", dbf_readfieldbyte_contents)
            self.assertIn("u rt_dbf_readbyte", dbf_readfieldbyte_contents)
            self.assertIn("r 89 u1", dbf_readfieldbyte_contents)
            dbf_writefieldbyte_contents = (lib_dir / "RT_DBF_WRITEFIELDBYTE.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_dbf_writefieldbyte 0 98", dbf_writefieldbyte_contents)
            self.assertIn("u rt_dbf_fieldlen", dbf_writefieldbyte_contents)
            self.assertIn("u rt_dbf_writebyte", dbf_writefieldbyte_contents)
            self.assertIn("r 95 u1", dbf_writefieldbyte_contents)
            dbf_append_contents = (lib_dir / "RT_DBF_APPEND.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_dbf_append 0 327", dbf_append_contents)
            self.assertIn("u rt_dbf_state", dbf_append_contents)
            self.assertIn("20 3C CF", dbf_append_contents)
            self.assertIn("r 322 u0", dbf_append_contents)
            dbf_pack_contents = (lib_dir / "RT_DBF_PACK.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_dbf_pack 0 233", dbf_pack_contents)
            self.assertIn("u rt_dbf_state", dbf_pack_contents)
            self.assertIn("u rt_dbf_pack_step", dbf_pack_contents)
            self.assertIn("u rt_dbf_pack_write", dbf_pack_contents)
            self.assertIn("r 228 u0", dbf_pack_contents)
            dbf_save_contents = (lib_dir / "RT_DBF_SAVE.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_dbf_save 0 229", dbf_save_contents)
            self.assertIn("u rt_dbf_state", dbf_save_contents)
            self.assertIn("20 2D CF", dbf_save_contents)
            self.assertIn("20 30 CF", dbf_save_contents)
            dbf_headerlen_contents = (lib_dir / "RT_DBF_HEADERLEN.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_dbf_headerlen 0 18", dbf_headerlen_contents)
            self.assertIn("u rt_dbf_state", dbf_headerlen_contents)
            self.assertIn("A2 05 BD", dbf_headerlen_contents)
            dbf_recordlen_contents = (lib_dir / "RT_DBF_RECORDLEN.OBJ").read_text(encoding="ascii")
            self.assertIn("x rt_dbf_recordlen 0 18", dbf_recordlen_contents)
            self.assertIn("u rt_dbf_state", dbf_recordlen_contents)
            self.assertIn("A2 07 BD", dbf_recordlen_contents)
            self.assertTrue((lib_dir / "UDOSDIR.TXT").is_file())

    def test_export_with_udos_tools_builds_actinfo_when_prereqs_exist(self) -> None:
        root = Path(__file__).resolve().parents[1]
        tool = root / "tools" / "export_udos_workspace.py"
        udos_labels = root.parent / "udos" / "build" / "udos-resident.labels"
        if not udos_labels.is_file():
            self.skipTest("UDOS resident labels not built")

        with tempfile.TemporaryDirectory() as tmpdir:
            output = Path(tmpdir) / "out"
            result = subprocess.run(
                [sys.executable, str(tool), "--output", str(output), "--build-udos-tools"],
                cwd=root,
                text=True,
                capture_output=True,
                check=False,
            )
            self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)

            image_root = output / "IMAGES" / "ACTION.DNP"
            self.assertTrue((image_root / "ACTDIR.PRG").is_file())
            tree_overlay = (image_root / "TREE.OVL").read_bytes()
            self.assertEqual(tree_overlay[:6], b"\x00\x09UDOV")
            self.assertEqual(tree_overlay[6:10], bytes((1, 6, 20, 0)))
            self.assertEqual(int.from_bytes(tree_overlay[10:12], "little"), 0x0900)
            self.assertGreaterEqual(int.from_bytes(tree_overlay[12:14], "little"), 0x090E)
            self.assertEqual(int.from_bytes(tree_overlay[14:16], "little"), len(tree_overlay) - 2)
            xcopy_overlay = (image_root / "XCOPY.OVL").read_bytes()
            self.assertEqual(xcopy_overlay[:6], b"\x00\x09UDOV")
            self.assertEqual(xcopy_overlay[6:10], bytes((1, 6, 21, 0)))
            self.assertEqual(int.from_bytes(xcopy_overlay[10:12], "little"), 0x0900)
            self.assertGreaterEqual(int.from_bytes(xcopy_overlay[12:14], "little"), 0x090E)
            self.assertEqual(int.from_bytes(xcopy_overlay[14:16], "little"), len(xcopy_overlay) - 2)
            deltree_overlay = (image_root / "DELTREE.OVL").read_bytes()
            self.assertEqual(deltree_overlay[:6], b"\x00\x09UDOV")
            self.assertEqual(deltree_overlay[6:10], bytes((1, 6, 22, 0)))
            self.assertEqual(int.from_bytes(deltree_overlay[10:12], "little"), 0x0900)
            self.assertGreaterEqual(int.from_bytes(deltree_overlay[12:14], "little"), 0x090E)
            self.assertEqual(
                int.from_bytes(deltree_overlay[14:16], "little"),
                len(deltree_overlay) - 2,
            )
            self.assertTrue((image_root / "ACTADD.PRG").is_file())
            self.assertTrue((image_root / "ACT2SAVE.PRG").is_file())
            self.assertTrue((image_root / "ACTSAVE.PRG").is_file())
            self.assertTrue((image_root / "ACTC.PRG").is_file())
            self.assertEqual((image_root / "ACTC_OVL0.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVL1.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVL2.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVL3.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVL4.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVL5.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVL6.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVL7.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVL8.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVL9.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLA.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLB.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLC.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLD.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLE.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLF.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLG.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLH.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLI.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLJ.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLK.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLL.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLM.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLN.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLO.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLP.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLQ.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLR.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLS.BIN").read_bytes()[:4], b"ACOV")
            self.assertEqual((image_root / "ACTC_OVLT.BIN").read_bytes()[:4], b"ACOV")
            self.assertTrue((image_root / "ALINK.PRG").is_file())
            self.assertTrue((image_root / "ACTCHK.PRG").is_file())
            self.assertTrue((image_root / "ACTMON.PRG").is_file())
            self.assertTrue((image_root / "ACTFILE.PRG").is_file())
            self.assertTrue((image_root / "ACTWORK.PRG").is_file())
            self.assertTrue((image_root / "ACTFLOW.BAT").is_file())
            self.assertTrue((image_root / "ACTNEW.BAT").is_file())
            self.assertTrue((image_root / "ACTNEW.PRG").is_file())
            self.assertTrue((image_root / "ACTSRC.PRG").is_file())
            self.assertTrue((image_root / "PROJECT.TXT").is_file())
            self.assertTrue((image_root / "MAIN.ACT").is_file())
            actnew_lines = (image_root / "ACTNEW.BAT").read_text(encoding="ascii").splitlines()
            self.assertTrue(actnew_lines)
            self.assertTrue(all(len(line) <= 31 for line in actnew_lines if line))
            self.assertTrue((image_root / "ACTINFO.PRG").is_file())
            self.assertTrue((image_root / "ACTCOPY.PRG").is_file())
            self.assertTrue((image_root / "ACTDEL.PRG").is_file())
            self.assertTrue((image_root / "ACTMKDIR.PRG").is_file())
            self.assertTrue((image_root / "ACTMOVE.PRG").is_file())
            self.assertTrue((image_root / "ACTRMDIR.PRG").is_file())
            self.assertTrue((image_root / "ACTWRITE.PRG").is_file())
            self.assertTrue((image_root / "ACTEDIT.PRG").is_file())
            self.assertEqual((image_root / "ACTEDIT_OVL1.BIN").read_bytes()[:5], b"AEOV\x02")
            self.assertTrue((image_root / "ACTDBG.PRG").is_file())
            self.assertEqual((image_root / "ACTDBG_OVL1.BIN").read_bytes()[:4], b"DGOV")
            self.assertEqual((image_root / "ACTDBG_OVL2.BIN").read_bytes()[:4], b"DGOV")
            old_vm_prefix = "A" + "VM"
            old_runner = old_vm_prefix + "RUN"
            for name in [
                old_vm_prefix + "INFO.PRG",
                old_runner + ".PRG",
                old_runner + "C.PRG",
                "RT_PRINT_STD_HELPER.BIN",
                "RT_PRINT_F_HELPER.BIN",
                "RT_GFX1_HELPER.BIN",
                "RT_SIDSPR1_HELPER.BIN",
                "RT_DBF1_HELPER.BIN",
                "RT_MATH1_HELPER.BIN",
                old_runner + "_OVL1.BIN",
                old_runner + "_OVL2.BIN",
                old_runner + "_OVL3.BIN",
            ]:
                self.assertFalse((image_root / name).exists(), name)


if __name__ == "__main__":
    unittest.main()
